# Innledning

## Hva er markdown?
Markdown er et enkelt system for å formatere *rentekst*. Rentekst er digital tekst i enklest mulig form - slik man kunne se på dataskjermer før Apple og Windows sine virtuelle skrivebord med grafiske brukergrensesnitt og klikk-og-pek kom på markedet. Rentekst kan lese av alle tekstprogrammer på alle datamaskiner, inkludert nettbrett og mobiltelefoner, og slike tekstprogrammer er gjerne gratis og tar svært liten plass. Rentekst-filer er også veldig små, siden de ikke inneholder noen annen informasjon enn bokstaver. Derfor er rentekst et veldig mobilt, fleksibelt og ikke minst billig tekstformat. Du produserer råtekst, bare inndelt i avsnitt: Det er ingen distraksjoner i skriveprosessen.

Imidlertid ønsker man jo som regel et eller annet grafisk design på teksten - overskrifter, avsnitt, kursiv, sentrering, osv. - for å gjøre den tiltalende og ryddig å lese. Det er her Markdown kommer inn som et alternativ til tekstbehandlingsprogrammer som Word. Markdown er rett og slett et enkelt sett med tegn og regler som man legger til helt vanlig tekst for å produsere elegante dokumenter, nettsider, lysbilder og elektroniske bøker. Med en helt kort kommando kan du fra én og samme rentekst-fil produsere et pent pdf-dokument, en ryddig nettside eller et Word-dokument som du eller andre kan jobbe videre med, hvis det er påkrevd. Denne elektroniske boken er for eksempel skrevet i markdown. Det er en billig, effektiv og veldig fleksibel måte å skrive alt fra notater til akademiske artikler og bøker. Og det er svært godt tilpasset en digitalisert tekst-verden, hvor vi hver dag jobber med digitale data og bruker en rekke ulike typer maskinvare og programmer for å lese tekst (PCer, nettbrett, mobiltelefoner, nettsider, Word-dokumenter, pdf-filer, PowerPoint-presentasjoner etc.). Når man skriver i markdown, bruker man enkle, raske tekstprogrammer som Notepad, hvor man skriver inn rå tekst og markerer enkel formattering, for eksempel **fete typer**, *kursiv* eller 

## overskrifter {.unnumbered} 

La meg illustrere poenget ved å vise hvordan den siste setningen over ser ut som rentekst:

```
Når man skriver i markdown, bruker man enkle,
raske tekstprogrammer som Notepad, hvor man skriver
inn rå tekst og markerer enkel formattering som 
**fete typer**, *kursiv* eller ## overskrifter.
```

## Hvorfor bruke markdown?
Det er mange grunner til at flere og flere akademikere har begynt å interessere seg for markdown. Her er noen som burde interessere alle:

- Det er få eller ingen distraksjoner når du skriver i markdown. Det er lettere å konsentrere seg kun om innholdet i teksten, og så kan du utsette innpakningen til senere med enkle grep. 
- Markdown er et mobilt format: Samme tekst kan enkelt brukes i ulike medier og presentasjonsformer (dokumenter, lysbilder, nettsider). Du vil alltid ha en "grunntekst" i et filformat som kan leses av all slags programvare.
- Teksten din varer "evig". Rentekst har eksistert siden datamaskinens fødsel, og vil aldri forsvinne eller blir foreldet. Dokumenter skrevet i rentekst i 1970 kan uten problemer leses nå og i all framtid. 
- Rentekst er solidarisk - den kan produseres og leses på de enkleste datamaskiner, med gratis programvare. Det finnes ingen mer tiltalende måte å dele akademisk kunnskap på.

I og med at de fleste av oss nå gjør mesteparten av jobben vår foran en datamaskin, er disse punktene ganske viktige. Det er verdt å sitere en artikkel om Markdown på nettstedet *Programming Historian* her:

>Å skrive, lagre og hente dokumenter er sentrale aktiviteter i humanistisk forskning. Likevel baserer mange forfattere praksisen sin på proprietære verktøy og formater som av og til ikke oppfyller de mest grunnleggende kravene til vitenskapelig skriving. Kanskje kan du kjenne deg igjen i frustrasjonen over skjørheten til fotnoter, bibliografier, figurer og bokutkast skrevet i Microsoft Word eller Google Docs.

Dersom du har litt interesse for datamaskiner og programvare, og til og med kunne tenke deg å snuse på hva programmering er, så finnes det enda flere grunner til å sette seg inn i Markdown:

- Gjennom å skrive i markdown-format forstår du mer av hvordan programvare og maskinvare virker, og du kommer deg ut av Microsoft- og Google-boblen og inn i et levende, fargerikt landskap av digitalhumaniora.
- Du frigjør deg fra Microsoft Word, et program som omgjør teksten din til et komplisert filformat med mengder av unødvendig informasjon og blander seg inn i teksten din med automatiske språk- og rettskrivingskontroller som er knotete å skru av og på. Hvem har vel ikke opplevd å få hele sideoppsettet rotet til fordi man skulle sette inn et enkelt lite bilde i et Word-dokument?
- Du får full kontroll over hvordan teksten din skal se ut - og du vil få en følelse av større kontroll over verktøyet ditt, altså datamaskinen og programvaren som følger med den.
- Kode (for eksempel Python og R, begge mye brukt av samfunnsvitere og humanister) skrives med rentekst, og med bruk av redigeringsprogrammer for rentekst. Gjennom å produsere vitenskapelig tekst med rentekst gjør du deg bedre kjent med konvensjoner og programvare som vil gjøre det enklere for deg å lære deg koding.

Hvis dette så langt virker tiltalende, er det god grunn til å lese videre. I dette lille kurset vil du lære alt fra hvordan du oppretter og lagrer et markdown-dokument til hvordan du kan produsere elegante artikkelmanuskripter, publisere pene e-bøker selv eller konstruere ryddige nettsider. Som en ekstra bonus vil du sannsynligvis også tilegne deg en systematisk og ryddig måte å organisere filene dine på, som er en stor verdi i seg selv.

## Videre lesning

- Dennis Tenen and Grant Wythoff: [Sustainable Authorship in Plain Text using Pandoc and Markdown](https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown), programminghistorian.org, 2022
