# 3 Referanser og referanseverktøy

## Forberedelser

- Last ned og installér [Zotero](https://www.zotero.org/). Installer også Zotero-tillegget for nettleseren din (Firefox, Chrome, Edge og Safari støttes)
- Last ned og installér [Better Bibtex Zotero-tillegget](https://retorque.re/zotero-better-bibtex/installation/) fra Retorque - følg installasjonsinstruksjonene slavisk og bruk standardinnstillingene.
- Opprett en mappe med navn "kap03" under mappen "markdownkurs".

## Opprette en tekstfil.

Vi starter med å opprette en .md-fil, for eksempel zoterotutorial.md. Inkludér følgende elementer i YAML-hodet:
```
---
tittel: din tittel
forfatter: deg
bibliografi: la dette elementet være tomt foreløpig, vi skal spesifisere det senere
---
```

Skriv noen setninger slik at du har noe tekst der du kan sette inn referanser.

OK. Da skal vi først omgjøre Zotero-referansene dine til rentekst-referanser og sende dem til mappen "kap03". Det gjør vi fra Zotero. 

## Hvordan eksportere Zotero-biblioteket til filmappen med din tekst

Først: Sørg for at du har klart for deg hvor i filsystemet filen zoterotutorial.md er: Du skal ha lagret den i mappen "kap03".

Åpne deretter Zotero. Hvis du har et bibliotek allerede, bra. Hvis ikke, lag et lite bibliotek nå bare for å øve deg. Gå til en hvilken som helst vitenskapelig database (for eksempel Google Scholar eller Oria gjennom UB) og velg boken/artikkelen du vil ha. Klikk deretter på bok-/artikkelikonet øverst til høyre i nettleseren din. Zotero-tillegget eksporterer nå referansen til biblioteket ditt. Etter at du har samlet nok referanser til å ha et lite bibliotek, skal du høyreklikke på biblioteket ditt i Zotero og velge "eksporter bibliotek."

(Hvis du har et stort bibliotek, vil du sannsynligvis bare eksportere en del av det, noe du kan gjøre ved å høyreklikke på den relevante mappen og velge "eksporter samling".)

- Velg Better Bibtex i rullegardinmenyen.
- Hvis dette er et pågående prosjekt, og du vet at Zotero-biblioteket ditt sannsynligvis vil utvide seg, velg "eksporter i bakgrunnen" og "hold oppdatert" alternativene. Dette sikrer at Zotero sender en oppdatert bibliografi til prosjektmappen din hver gang du gjør endringer.
- Nå kommer delen hvor du velger *hvor* du skal eksportere filen. *Velg den eksakte mappen hvor den nye .md-filen din er plassert.*
- Du har nå en .bib-fil som har samme filnavn som navnet på Zotero-samlingen du eksporterte. Sjekk om den er på rett sted.

Hva har vi egentlig gjort her? Zotero lagrer referanser i et format som enkelt kan eksporteres til rentekst, samtidig som alle metadata (forfatter, årstall, tittel, etc.) beholdes. Dette formatet, .bib, gjenkjennes av mange ulike programmer. Pandoc har en "siteringsmaskin", en såkalt "citeproc", som leser slike .bib-filer og kan formatere innholdet på en slik måte at man får ut ferdige, vitenskapelige bibliografier og referanser, enten det er fotnoter eller parenteser. .bib-filen vi nettopp eksporterte fra Zotero til arbeidsmappen din inneholder råmaterialet som Pandoc senere skal prosessere og lage fine referanser av. 

Men først må vi gi beskjed om hvor i teksten vi vil sette inn referansene! Det kommer nå.

## Sette inn Bedre Bibtex-referanser i Markdown

La oss først se på hvordan vi skriver referanser. Du bruker firkantklammer, en krøllalfa og deretter referansenøkkelen fra Zotero (gå til Zotero og kopier referansenøkkelen du vil prøve). For demonstrasjonens skyld har jeg inkludert et avsnitt fra en artikkel jeg skrev nylig. Her er det:

``` {style="background: gray"}
Vi mangler fortsatt gode forklaringer på fremveksten og funksjonene til CT-er i arabisk diskurs. Selv om litteraturen om CT-er av og til inkluderer Midtøsten og andre ikke-vestlige kontekster og erfaringer, f.eks. [@Butter2014;@Gurpinar2019;@Nefes2019;@Koerber2018], så er det 1900- og 2000-tallets Vest-Europa og USA som tjener som teori-grunnlag for CT-studier. Andre steder og tider måles mot modellen utviklet fra studier av moderne vestlige land og behandles som interessante varianter. I en eksemplarisk selvkritisk kommentar hevder Butter og Knight [@Butter2020b] at nåværende forskning er for fokusert på USA og samtidsperioden, og behandler CT-er altfor ofte som mestringsmekanismer for marginaliserte grupper. Vår forståelse av konspirasjonsdiskursen i det arabiske Midtøsten er i stor grad rammet av for mye anekdotisk bevis og for lite forskning. Den lille mengden forskning om konspirasjonsteorier i den arabiske Midtøsten og Nord-Afrika har ikke holdt tritt med utviklingen i litteraturen de siste 20 årene. Det finnes to monografier om emnet. Den ene heller mer mot paternalistisk polemikk enn forskning [@Pipes1996]. Den andre er seriøs og nyttig, men den behandler den arabiske offentlige sfæren som et atypisk tilfelle og fokuserer bare på etterkrigstiden. Et mer fundamentalt problem er at den ikke undersøker kilder på arabisk og derfor ikke kan gi en fullstendig forståelse av fenomenet [@Gray2010]. Det finnes verdifulle, mindre studier om CT-er i forhold til spesifikke problemstillinger. I tradisjonen med konspirasjonsforskning i kulturstudier bidrar Koerber med en studie av konspirasjon i egyptisk litteratur [@Koerber2018]. De Poli gir en utmerket undersøkelse av hvordan antisemittiske ideer, spesielt de i de fabrikkerte *Sions vises protokoller*, ble injisert i den arabiske offentlige sfæren gjennom fransk-influert katolisisme og senere nazistiske agenter [@DePoli2014]. Andre studier inkluderer konspirasjonsteorier i borgerkrig [@Silverstein2002], ideologisk strid og sekterisme [@Farha2016].
```

Når det kompileres til .html-format, vil det se ut som avsnittet nedenfor, og dersom kildene du henviser til finnes i zotero-biblioteket du lastet ned til mappen "kap03", vil en liste over referanser bli lagt til nederst i dokumentet (ta en titt på slutten av denne teksten for å se det).

Vi mangler fortsatt gode forklaringer på fremveksten og funksjonene til CT-er i arabisk diskurs. Selv om litteraturen om CT-er av og til inkluderer Midtøsten og andre ikke-vestlige kontekster og erfaringer, f.eks. [@Butter2014;@Gurpinar2019;@Nefes2019;@Koerber2018], så er det 1900- og 2000-tallets Vest-Europa og USA som tjener som teori-grunnlag for CT-studier. Andre steder og tider måles mot modellen utviklet fra studier av moderne vestlige land og behandles som interessante varianter. I en eksemplarisk selvkritisk kommentar hevder Butter og Knight [@Butter2020b] at nåværende forskning er for fokusert på USA og samtidsperioden, og behandler CT-er altfor ofte som mestringsmekanismer for marginaliserte grupper. Vår forståelse av konspirasjonsdiskursen i det arabiske Midtøsten er i stor grad rammet av for mye anekdotisk bevis og for lite forskning. Den lille mengden forskning om konspirasjonsteorier i den arabiske Midtøsten og Nord-Afrika har ikke holdt tritt med utviklingen i litteraturen de siste 20 årene. Det finnes to monografier om emnet. Den ene heller mer mot paternalistisk polemikk enn forskning [@Pipes1996]. Den andre er seriøs og nyttig, men den behandler den arabiske offentlige sfæren som et atypisk tilfelle og fokuserer bare på etterkrigstiden. Et mer fundamentalt problem er at den ikke undersøker kilder på arabisk og derfor ikke kan gi en fullstendig forståelse av fenomenet [@Gray2010]. Det finnes verdifulle, mindre studier om CT-er i forhold til spesifikke problemstillinger. I tradisjonen med konspirasjonsforskning i kulturstudier bidrar Koerber med en studie av konspirasjon i egyptisk litteratur [@Koerber2018]. De Poli gir en utmerket undersøkelse av hvordan antisemittiske ideer, spesielt de i de fabrikkerte *Sions vises protokoller*, ble injisert i den arabiske offentlige sfæren gjennom fransk-influert katolisisme og senere nazistiske agenter [@DePoli2014]. Andre studier inkluderer konspirasjonsteorier i borgerkrig [@Silverstein2002], ideologisk strid og sekterisme [@Farha2016].


\

For at dette skal fungere i ditt dokument, må du fylle ut bibliografi-feltet i YAML-hodet. Filnavnet på bibliografien i dette eksempelet er konspirasjoner.bib. Du kan sjekke ditt eget filnavn i mappen der du lagret bibliografifilen til. Skriv det fulle filnavnet nøyaktig slik det vises (YAML er følsomt for store og små bokstaver).

Dette YAML-feltet forteller Pandoc at den skal hente referansene du har inkludert i markdown-teksten din fra denne filen.

## Kompilering av .html/.pdf/.docx-filen

Nå er vi ferdige!

- Lagre .md-filen din slik at du er sikker på at de siste endringene du gjorde er inkludert.

- Åpne terminalen i samme mappe som .md-filen din og .bib-filene dine er.

- Gi Pandoc følgende kommando:

```
pandoc --citeproc filnavnetditt.md -s -o filnavnetditt.html
```


Prøv det nå med forskjellige filformater!

## Velg mellom sitatstiler

Dette er *ekstremt* nyttig. Du kan konvertere referanser og bibliografi til nesten hvilken som helst stil automatisk, bare ved å fortelle programmene du bruker hvilken stil du ønsker. Slike stiler har filnavnet *.css. Jeg limer inn en maskinoversatt seksjon fra Pandocs brukerveiledning:

>Sitater og referanser kan formateres ved hjelp av hvilken som helst stil som støttes av Citation Style Language (csl), oppført i Zotero Style Repository. Disse filene spesifiseres ved hjelp av --csl alternativet eller csl (eller citation-style) metadatafeltet. Som standard vil pandoc bruke Chicago Manual of Style forfatter-dato format. (Du kan overstyre denne standarden ved å kopiere en CSL-stil etter eget valg til default.csl i brukerdatakatalogen din.) CSL-prosjektet gir ytterligere informasjon om å finne og redigere stiler.

Så hvis du vil spesifisere en sitatstil, laster du ned csl-stilen du ønsker fra Zotero-databasen [her](https://www.zotero.org/styles) og plasserer den i mappen der tekstfilen din er, og deretter inkluderer du den i YAML-hodet:

    ---
    bibliography: din .bib-fil
    csl: digital-scholarship-in-the-humanities.csl
    ---